'use client';
import type { Metadata } from 'next';
import styles from "../style/styles.module.css";
import { FirebaseContext } from '@/context/firebase'
import { firebase, auth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from '@/lib/firebase'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={styles.html} lang="en">
      <body className={styles.body}>
        <FirebaseContext.Provider value={firebase, auth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged}>
          {children}
        </FirebaseContext.Provider></body>
    </html>
  )
}
