import type { Metadata } from 'next';
import styles from "../style/styles.module.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={styles.html} lang="en">
      <body className={styles.body}>{children}</body>
    </html>
  )
}
